### ISSUE TITLE
'make' depends on state of GOPATH

### ISSUE THREAD

**Issue by jmank88** [twitchtv/twirp#17]
[CONTRIBUTING.md](https://github.com/twitchtv/twirp/blob/master/CONTRIBUTING.md) states:
```Generally you want to make changes and run make, which will install all dependencies we know about...```
but I experienced build failures (with no changes).  However, running `dep init` to vendor dependencies first led to a successful run of `make`, suggesting something in my `GOPATH` was incompatible/outdated and not updated by `make`.

- Are there additional dependencies to install/update via `make`?
- Alternatively, could a `dep` manifest and/or vendor directory be used to stabilize dependencies? (or would that clash with the rest of `make`, which is built around `GOPATH` and `go install`?)

**Comment by jmank88** [comment]
`dep init` produced:
```toml
[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
```
